name: build kernel

on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查储存库
        uses: actions/checkout@v4

      - name: 下载llvm
        run: |
          wget https://android.googlesource.com/platform//prebuilts/clang/host/linux-x86/+archive/b669748458572622ed716407611633c5415da25c/clang-r416183b.tar.gz
          tar -q -zxf clang-r416183b.tar.gz
          mv clang-r416183b.tar.gz llvm12
          
      - name: 添加KernelSU Next
        run: |
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s legacy

      - name: 执行build.sh
        run: |
          chmod +x build.sh
          ./build.sh

      - name: 上传AnyKernel3刷机包
        uses: actions/upload-artifact@v4
        with:
         name: kernel-zip
         path: out/kernel.zip
